### ISSUE TITLE
Change loading icon to Skeleton

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#1]
In the search tab, there is a loading spinner that waits to receive data from the backend.

The proposal is to change to the Skeleton model so that it is in the same format as our articles.

Source: https://quasar.dev/vue-components/skeleton#introduction

### Before
<img width="400" alt="Captura de Tela 2022-10-31 às 15 33 22" src="https://user-images.githubusercontent.com/26576201/199083719-25edbc3e-8f3f-48c0-aea8-a189e1d6360f.png">

### After
<img width="316" alt="Captura de Tela 2022-10-31 às 15 34 12" src="https://user-images.githubusercontent.com/26576201/199083730-a7c95de6-7376-45c6-a884-a07ac35b8742.png">

**Comment by stravid87** [comment]
Great idea! A simple mind trick to make our app more engaging and friendly.
