### ISSUE TITLE
Local storage cache(?) doesn't update even after store does.

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#101]
When navigating back to the page, I need to trigger a (what I think is prompt store refresh?) before the content displays. Local storage doesn't seem to update automatically with updating the prompt store.

To recreate:
1) Set local store to have less than what's in Firestore. Leave the site and then navigate back to the Search page. You'll see what's in the local storage only. Trigger Pina promptStore to load (I assume?) and then you'll see all the prompts but local storage will not update.

**Comment by stravid87** [comment]
![LocalStorage_Bug](https://user-images.githubusercontent.com/116566901/218228989-4160abbd-431c-4f19-8879-0a335514e672.png)

**Comment by stravid87** [comment]
@arnonrdp  I think this one's for you.

**Comment by arnonrdp** [comment]
@stravid87, I just updated it.

Can you try to reproduce it in `develop` branch?

**Comment by stravid87** [comment]
Hmmmm, works in develop. Maybe because the app storage is reset with each run of `npm dev`?

**Comment by stravid87** [comment]
Loaded on a new computer here in Ft. McMurray it works fine. 
It must be a local storage issue / local data issue?
Let's park it until it happens consistently. Strange glitch on my end..,

**Comment by arnonrdp** [comment]
No, actually there was really a improvement to be done in `SearchPage.vue`.

I did this only on the `develop` branch. Do you want me to make this adjustment in the prod too?

**Comment by stravid87** [comment]
No no. No worries. At your pace. We can do a roll out with max number of changes. I keep delaying sharing the link. Really, it's only us looking right now.

**Comment by arnonrdp** [comment]
Noted. I am closing then.
