### ISSUE TITLE
Setup Sentry Dashboard for the project

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/Celebrity-Fanalyzer#104]
Sentry would provide us with real-time visibility into any production issues, allowing us to quickly identify and resolve any bugs, crashes, or performance degradation. This would improve the overall stability and user experience of the application, as well as prevent similar issues from happening in the future.

Sentry also provides detailed error reports, including stack traces and context information, making it easier for us to diagnose and reproduce bugs. With Sentry's integration with Quasar and other tools, such as Slack and GitHub, it's easy to set up and use, saving us time and effort.

I know some of you might be thinking, "Do we really need another tool in our stack?" But trust me, Sentry will not only make our lives easier, but it will also ensure that our Vue.js/Quasar project is running smoothly and providing a positive experience for our users. So let's give it a try and see how it can help us improve our workflow and product.

PS: I use Chat GPT to generate the description of the issue.

**Comment by arnonrdp** [comment]
I think it's a good idea to set a deadline for Sentry.
It would be like saying, "Sentry, you'll stay with us and show us everything that's wrong until X month, after which we won't need you anymore. Thank you."

So I'm going to merge it and then we'll talk about its progress and the errors it encounters. Once it's not finding anything else wrong we'll know we don't need it anymore.

From there we can remove the code and dependencies that are no longer used.

**Comment by hermannleboss** [comment]
I agree
