### ISSUE TITLE
Search Functionality Improvement

### ISSUE THREAD

**Issue by NJavokhir** [globe-and-citizen/Celebrity-Fanalyzer#109]
When using the search functionality, It can't accommodate typos. It's also not obvious that it's only the title. I'm not sure how to do this but presumably it should consider entries and prompts. The titles and the inner content + tags.

**Comment by arnonrdp** [comment]
Very good issue, @NJavokhir.
All the information you mentioned we already have in Pinia State, so I think it will work.

You will probably be working on the `const computedPrompt`, my only request is that changes made to `SearchPage.vue` also be carried over to `YearArchivePage.vue`.
