### ISSUE TITLE
Add Cypress to our Tests

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#125]
Now that we have tests running, we need a powerful tool to use during testing.

After our discussions, we opted for Cypress.

  - https://www.cypress.io/
  - https://testing.quasar.dev/packages/e2e-cypress/

```[tasklist]
### Tasks
- [x] Setup cypress
- [x] Cypress CI/CD with github action
- [ ] Cypress Record
```

**Comment by arnonrdp** [comment]
@hermannleboss, are you working on this last task?

**Comment by hermannleboss** [comment]
Yes
