### ISSUE TITLE
Improvements to the CMS

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#126]
Over time, our CMS (Content Management System) will need to become more sophisticated to that _any_ user finds it easy.

For the next release, one of the ideas is to bring the collection of errors into the application. That way, it would not be necessary to access the bank in search of them. It would be easier to find and solve them.

Another proposal would be to bring all the content that is in Firebase Storage and a way to know if these images are in use or not. I haven't quite defined the ideas of how this would work, at this point it's just a proposal.

We'll discuss this next Saturday.

**Comment by stravid87** [comment]
What do you mean by this? 
"For the next release, one of the ideas is to bring the collection of errors into the application."

As for the storage: yes. Immediately less concerning. In time: very concerning!

**Comment by arnonrdp** [comment]
I meant the collection **errors** in Firestore. Because it's never a good idea to be accessing the database every time.

**Comment by stravid87** [comment]
Ahhh got you. Like a store, errors.js, where the errors collect and then report.

**Comment by arnonrdp** [comment]
Exactly
