### ISSUE TITLE
Ensuring a robust feedback system for users.

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#127]
> @stravid87:
> Wandering through the internet, I've noticed a pattern: successful institutions and businesses and site have robust, open, feedback mechanisms.
> 
> (Also worth noting, companies with near monopoly status have terrible / non-existent feedback systems! I.e., insurance companies, banks, etc)
> 
> ![Image](https://user-images.githubusercontent.com/116566901/216770219-10d641e4-5e92-4043-8b40-1193be3694c4.png)

**Comment by arnonrdp** [comment]
I just uploaded a first user feedback system.

It's still not robust but we can talk about having more fields and since the hard part is done it will be simpler to add them.

**Comment by stravid87** [comment]
I've added this to my discussion points for tomorrow .
