### ISSUE TITLE
Develop tests that create a Prompt and an Entry

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#142]
I believe the next big step in testing is creating Prompts and Entries.

This will save us time because instead of having to create a Prompt/Entry and see if everything is working, we can just run the tests and see if everything works as expected.

```[tasklist]
### Tasks
- [x] Create Prompt
- [x] Delete Prompt
- [x] Create Entry
- [x] Delete Entry
```

**Comment by stravid87** [comment]
I agree. Let's merge now. Then, in April, we'll focus on Quality > Quantity.

**Comment by stravid87** [comment]
I agree. Let's merge now. Then, in April, we'll focus on Quality > Quantity.
