### ISSUE TITLE
[BUG] Comment, Like, Share Tallies Below 'Entry' on First Load 

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#159]
**Describe the bug**
When an entry page is loaded, the image populates immediately and the components start to pull in and load. 
In the background the likes, dislikes, and comments are loading. At this moment, the counts are reflected as Likes 0, Dislikes 0, Comments 0. Eventually, they populate to be the correct numbers.
 
**To Reproduce**
1. Go to ''any entry, any page"
2. Scroll to the bottom quickly'
3. Watch the numbers populate in. 

**Screenshots**
Unnecessary.

**Smartphone (please complete the following information):**
 - Device: ALL
 - OS: ALL
 - Browser ALL

**Additional context**
This is NOT a high priority issue. It might break other code fixing it.  Alternatively, trying to apply a simple fix (like a loading spinner for every stat) could cause code bloat. Time can creativity and cleverness can be taken to address this small issue / bug.

**Comment by arnonrdp** [comment]
I just created this CodePen: https://codepen.io/arnonrdp/pen/bGxyoYB

Let me know your thoughts on having something like this as a loading for the counters.

**Comment by arnonrdp** [comment]
@stravid87 let me know your thoughts on the load times and if you think this issue still needs work.

**Comment by stravid87** [comment]
I no longer see this happening -- appears to have been fixed.
