### ISSUE TITLE
Make tests more robust

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#163]
Right now we have tests running with the main features we need in our application.

So we probably won't have any new tests running in the next release.

The next step is to make our tests more robust in the sense of:
- work to avoid common and constant mistakes;
- follow the recommended practices in the documentation;
- make sure to keep our test documentation up to date so that no one has any questions about how to run them.

I understand that this is not the responsibility of just one developer, but of all of us, so I assigned this task to the four of us.

Sources:
https://docs.cypress.io/guides/references/best-practices

---

Create your specific branches from the `develop` branch and use the `testing` prefix.
For example: `testing/comments-Javokhir`

Any new idea is welcome, share your opinions.

**Comment by stravid87** [comment]
I totally agree with tagging all of us. My thought, as I told Hermann today, was as everyone: Every week to contribute 1 "it block" (i.e., 1 test / week) until our code coverage increases to 100%. Can be very simple. Just 1 each.

By release 1.3 / 1.4, I'm hoping we've all gotten adequately comfortable to require that ANY new functionality gets merged WITH it's test at the time of merging into develop. That is, writing tests is just part of writing functionality. No test? No merge. 

I don't want it to become an afterthought.
