### ISSUE TITLE
[BUG] Changing Profile Picture

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#173]
**Describe the bug**
When attempting to change the profile picture, if a large picture is uploaded, the change will show but then not save. Upon reload, it will be the same previous picture.  

**To Reproduce**
Change the profile picture to a large picture by file size. Save and reload. Firebase will not update and a subtle error will show in the console. 

**Screenshots**
https://user-images.githubusercontent.com/116566901/232222486-b795fe0f-769c-49e7-8b62-3b10012517b4.mp4

**Smartphone (please complete the following information):**
- Browser, chrome
- Mobile (OS unknown)

**Request / Fix
Warning or user feedback when a picture too large is uploaded preventing any updates to the UI until an appropriately sized picture is chosen.

**Comment by arnonrdp** [comment]
@stravid87, it is already merged but can you please test it in production?

**Comment by stravid87** [comment]
> @stravid87, it is already merged but can you please test it in production?

Yup.... let me do it now.

**Comment by stravid87** [comment]
What is the expected behavior / limit? 
![image](https://user-images.githubusercontent.com/116566901/236098436-016a0611-e3f9-4947-ab11-7ad8fa534ec5.png)
This image is 21MB -- obviously gigantic. What limit do you intend?
