### ISSUE TITLE
Organization of roles

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#187]
> Ultimately the goal is to NOT track users. That is, let everyone be anonymous breaking the link between their true identity and their online identity. A step in this direction will be to allow them to login without needing to do so via a large provider: Google, Facebook, LinkedIn, etc.
"@stravid87"

---

Let's define the following roles and permissions:

### Anonymous
User who accessed and decided not to authenticate.
- Can comment, like, dislike and share.

### User
User who authenticated but never wrote anything.
- Can set name and profile picture, add biography and other data;
- You can set a username and have your own public page.

### Writer
User who requested to be a writer and was accepted.
- Can write entries.

### Editor
Writer who was selected by the Team.
- Can write prompts;
- Has access to Feedbacks;
- Can edit and remove prompts and entries.

### Admin | Developer
Team users working on application development.

**Comment by stravid87** [comment]
Feel free to delay this in favor of refactoring state mgt and working on speed optimizations. There won't be any "real" users for the foreseeable future (likely on the order of months still)

**Comment by arnonrdp** [comment]
@stravid87, I just moved it to develop.

Can you test it and, if it's ok, close the issue?

**Comment by stravid87** [comment]
> 

Yup -- let me look tmr. At this point in the evening my brain is getting foggy haha

**Comment by stravid87** [comment]
When signing up with email, I seem to be getting a recurring error => "errors.js:53 Uncaught (in promise) Error: FirebaseError: [code=invalid-argument]: Function setDoc() called with invalid data. Unsupported field value: undefined (found in field displayName in document users/x56SXGVgXlQA5t972aYYGbJabgk2)" 

I have changed the name to nothing, spaces, no spaces, caps and no caps.

**Comment by stravid87** [comment]
Anonymous signing in work. But it offers near equivalent functionality. 
... you're going to hate me but I think we need to reverse these changes. Seeing this work makes me realize that I have a lot more work to do in terms of figuring out flow. This login process will be fundamental so I think we need to give it adequate time and push it to June developement.

**Comment by arnonrdp** [comment]
No worries, I completely understand.
First, we need to define permissions for each type of user.

**Comment by stravid87** [comment]
Allowing users to log in with email is adequate. 
No need to log in "anonymous" this is the default: anyone NOT logged in IS anonymous.
