### ISSUE TITLE
Optimize Application Speed

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#188]
The site still has some kind of overload.

The idea that came to me for now is to focus on state management so that users/writers see the changes and then send them to the DB.

Is it time to try `indexedDB`?

**Comment by arnonrdp** [comment]
@stravid87 could you check the speed of things in the `develop` environment?

If it's good, can you close this issue, please.

**Comment by stravid87** [comment]
> @stravid87 could you check the speed of things in the `develop` environment?
> 
> If it's good, can you close this issue, please.

Yup. Let me do it right now.
