### ISSUE TITLE
[BUG] CSS Rendering of "Entry" Bottom

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#194]
**Describe the bug**
When using Edge or Firefox, if the user scrolls to the page bottom, they can see a sliver of the background picture. 

**To Reproduce**
1. Use Edge or Firefox 
2. Scroll to the bottom of an entry. 

**Screenshots**
![image](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/116566901/babe6607-2175-48db-b715-9f70bd809ce0)

**Environment**
Windows laptop, Edge and Firefox

**Comment by arnonrdp** [comment]
@NJavokhir, as I refactored prompts and entries I ended up solving this issue.
