### ISSUE TITLE
[BUG] When try to navigate to admin page :  error  Duplicated key 'date'  vue/no-dupe-keys

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/Celebrity-Fanalyzer#206]
**Describe the bug**

**To Reproduce**

1. Go to Home page'/'
2. Click on 'Admin Page'

**Screenshots**
![image](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/28951070/c1524b25-5db4-468c-b1fa-1f90a921d305)

**Desktop Windows 10**

- Device: Desktop
- OS: Windows 10
- Browser Brave

**Additional context**

**Comment by arnonrdp** [comment]
Thanks for reporting, @hermannleboss.

I am on it.
