### ISSUE TITLE
Create Full Documentation to Make Participation and Development Easier

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#21]
I'm going to starting working in on this. Specifically, building out an architectural document to show the big picture.

**Comment by stravid87** [comment]
UPDATE: The application is now running locally on my machine with a separate Firebase back end that I set up and a different set of .Env variables. My next step is to harden the Firestore rules so that we can open it up as basically a Celebrity Fanalyzer Dev Api.

**Comment by arnonrdp** [comment]
Sounds really great!

**Comment by arnonrdp** [comment]
Hey guys, are you still working on this issue?

**Comment by stravid87** [comment]
For now, I think this issue can be closed. I think further work on the documentation will come at the next inflection point (that is the next round of hiring). I don't think it will be too relevant until then so this issue could be closed.
