### ISSUE TITLE
[BUG] Do not scroll the page when exiting the showcase

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#214]
1. Click on showcase view;
1. Exit the view;
1. See the page return to the top and scroll down.

Fix the transient scrollbars when viewing the carousel as well.

---

### EDIT

A possible solution was posted in here: https://discord.com/channels/415874313728688138/806171748046733332/1122832476885241976

But I was not able to apply it.

**Comment by arnonrdp** [comment]
Guys, I'm really stuck with this task.
See what I've done so far:

I added these event in `q-dialog`:

```html
<q-dialog position="top" v-model="openDialog" @before-show="beforeShow" @show="show" @before-hide="beforeHide" @hide="hide">
```

Also, I added these functions:

```js
function beforeShow() {
  console.log('before-show', window.scrollY)
}

function show() {
  console.log('show', window.scrollY)
}

function beforeHide() {
  console.log('before-hide', window.scrollY)
}

function hide() {
  console.log('hide', window.scrollY)
}
```

This is the result:

https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/26576201/eb79b4c0-c9e0-4847-b738-f3c6e242327f

---

After looking at these 4 console.logs, I forced the window to stay in the same position, like this:

```js
function beforeShow() {
  scrollPosition.value = window.scrollY
  window.scrollTo({ left: 0, top: scrollPosition.value, behavior: 'auto' })
  console.log('before-show', window.scrollY)
}

function show() {
  window.scrollTo({ left: 0, top: scrollPosition.value, behavior: 'auto' })
  window.scrollY = scrollPosition.value
  console.log('show', window.scrollY)
}

function beforeHide() {
  console.log('before-hide', window.scrollY)
}

function hide() {
  console.log('hide', window.scrollY)
}
```

And this was the result:

https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/26576201/f4f5ccc7-06b3-419e-8bb1-7b0e5f99b263

As you can see, the console.log displays the desired value (the distance from the top of the window), but when the dialog is hidden, it goes back to the top and scrolls down again.

**Comment by 0336328069** [comment]
Hi bro, I don't know if you have fixed this error yet!

**Comment by arnonrdp** [comment]
> Hi bro, I don't know if you have fixed this error yet!

No, this is not fixed yet.
@0336328069 , do you know how to fix it?
