### ISSUE TITLE
[BUG] Unable to display entries from prompt page

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/Celebrity-Fanalyzer#241]
**Describe the bug**
Unable to display entries from prompt page

**To Reproduce**

1. Go to http://localhost:9200/lost-series-from-2000s
2. Click on one entry

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Windows 10
- Browser Brave

**Comment by arnonrdp** [comment]
@hermannleboss, can you confirm this issue?
I couldn't reproduce it here.

**Comment by hermannleboss** [comment]
I do not have access to my computer right now. Will work on it in 2 hours

**Comment by hermannleboss** [comment]
I don't see it again
