### ISSUE TITLE
Report comment

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#254]
As we get bigger, it's normal for unwanted users to comment unwanted things.

That's why I think it's important for users to be able to report comments from other users.

We must then create a new tab in the administration area for all reports.
From there, admins can remove the comment.

**Comment by hermannleboss** [comment]
It's  will good if Admin can remove or hide comment

**Comment by NJavokhir** [comment]
Hmm, interesting issue, I am gonna eat it.

**Comment by arnonrdp** [comment]
> Hmm, interesting issue, I am gonna eat it.

We need to check with @stravid87 first. Perhaps all issues are postponed.

**Comment by arnonrdp** [comment]
That said, I moved this issue and also #234 and #275 back to Backlog.

In the next release we will only focus on #284.

**Comment by arnonrdp** [comment]
> Hmm, interesting issue, I am gonna eat it.

@NJavokhir, your time to shine has come.
