### ISSUE TITLE
[BUG] Error On VisitorsBar 

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/Celebrity-Fanalyzer#262]
**Describe the bug**
There is an error on the prompts pages du to Visitors Bar

**To Reproduce**

1. Go to '/month'
2. Navigate to Anthrogram 
3. See error
![image](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/28951070/afc4fa5a-9106-4e43-899e-09cc22492a67)

**Screenshots**

**Additional context**

**Comment by arnonrdp** [comment]
@hermannleboss, I pushed a fix.

Can you check again?

**Comment by hermannleboss** [comment]
Yes it's fixed
