### ISSUE TITLE
[BUG] Non-anonymous user treated as anonymous

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#265]
I don't know if it's possible to reproduce, but sometimes a logged in user makes a comment and it is treated as anonymous.

In the example below, the comment was made by Taiba:

<img width="1680" alt="Captura de Tela 2023-07-07 às 15 18 03" src="https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/26576201/8136a197-412a-4d82-b9db-5f1636f0f437">

<img width="1265" alt="Captura de Tela 2023-07-07 às 15 19 01" src="https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/26576201/4093b368-782c-40db-9dcf-8e90ba72692c">

**Comment by hermannleboss** [comment]
I find where the problem comme from. And it's not only fo comment. 
The getter isAnonymous is wrong so everywhere it's used we have the error. 

![image](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/28951070/19b35bb1-fbb4-4ccc-8fed-54c828f4350f)

**Comment by arnonrdp** [comment]
Great!
It is not only in `prod`, the error also occurs in `develop`

**Comment by arnonrdp** [comment]
@hermannleboss, to be more specific, the error is actually in here:

![Captura de Tela 2023-07-10 às 15 07 29](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/26576201/59b1fca1-9fbf-4aa6-abc5-7cda40e09d06)

We cannot get an user by id if the user was not retrieved from the DB.

How would you solve this issue without slowing down the entire component?

**Comment by hermannleboss** [comment]
Thanks

**Comment by arnonrdp** [comment]
@hermannleboss, can you test on your end to make sure it works?
