### ISSUE TITLE
Group similar notifications

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/Celebrity-Fanalyzer#275]
> All comment in a notification that is related to an Entry or a Prompt should be readed if we open one
~ by Hermann

---
### Edit: by Arnon

Perhaps we should improve the way notifications are stored.
For example, if there are more than one notifications coming from the same place, they could be merged.

As I discussed with Ravi earlier we won't be bringing any new features in this release, so I'll move this issue to the next release.

**Comment by arnonrdp** [comment]
This needs to be discussed.
Perhaps we should improve the way notifications are stored.
For example, if there are more than one notifications coming from the same place, they could be merged.
What do you think?
