### ISSUE TITLE
[BUG] User who would like to become writers are able to submit requests. However, admins are not able to okay those same requests.

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#279]
**Describe the bug**
User who would like to become writers are able to submit requests. However, admins are not able to okay those same requests. 

**To Reproduce**
1. Create a new user. 
2. Login as that user. 
3. Request to become a writer.
4. Log out
5. Log in with another user that is admin. 
6. Attempt to okay the first user just created. 
7. An error stating "vue.c3f211a5.js:1 TypeError: r.acceptWriter is not a function" will appear in the console.

**Screenshots**
![accptingWriterError](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/116566901/aefd340c-47b2-4688-a5b0-9f3622e9ae0d)

**Smartphone (please complete the following information):**
- Windows
- Chrome

**Comment by arnonrdp** [comment]
Obs.: This needs to be tested in `develop` branch.
