### ISSUE TITLE
Wrong Process of fetching data

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/Celebrity-Fanalyzer#289]
**Is your feature request related to a problem? Please describe.**
For Every Entry or prompt, we fetch all his comments, likes, dislikes, shares, and visitors that lead a big amount ou read on firestore. 

Ex: For one prompt we have
- 2 Likes
- 51 Dislikes
- 145 Comments
- 49 Share
- 116 Visites for 61 Visitores
- Total 424 Reads For Every User, that is too much. 
![image](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/28951070/398947ea-3cbc-4021-b265-6d175fe504cc)

![image](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/28951070/ce94e034-8ee2-4b2c-bb31-1ae7fb8f352c)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arnonrdp** [comment]
@hermannleboss we need to figure out how to enhance this.

**Comment by arnonrdp** [comment]
Hermann, you've brought us something that doesn't look good.

Do you have any suggestions on how to improve this?

**Comment by hermannleboss** [comment]
I'm studying it. Right now I don't have a solution

**Comment by arnonrdp** [comment]
@hermannleboss, I don't think this process is wrong.

**Comment by hermannleboss** [comment]
@arnonrdp i don't think so.
