### ISSUE TITLE
[BUG] Editors are not being fetched

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#291]
**Describe the bug**
When looking at the entries below a prompt, the author attributions are showing as anonymous avatars. 
Of note, there was NO such but until I logged out and viewed it as an anonymous user. 

**To Reproduce**
View the entries below a prompt.
Look at the author attributions. 
Next, log out and view again as an anonymous user. 
The attributions should now be incorrectly anonymous. 

**Screenshots**
<img width="510" alt="image" src="https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/116566901/18217a5b-84f6-4737-98e9-94cb8c5a1201">

**Smartphone (please complete the following information):**

- OS: Windows
- Browser: Chrome

**Additional context**
Laptop

**Comment by arnonrdp** [comment]
@stravid87, I committed a fix. Can you check this again?
