### ISSUE TITLE
Labeling Post / Content Details

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#3]
To more easily distinguish the views and app content during development, my thought is to put the label [Entry] & [Prompt] in the headings. For example,

"When you are on beach next time, think just this one" => "[Prompt] When you are on beach next time, think just this one." 

This is purely the addition of words. No CSS. No Animations required. Unnecessary when the app launches because, in time, the components used to house the prompt cards (i.e., those on the home page), may need to be distinguished from those of the entries (i.e., those underneath the Topic Detail / Prompt)

**Comment by arnonrdp** [comment]
That makes sense and I like this idea.

But before proceed, let me ask: what should we do if a post have more than one category? We define a category as primary or something different?

Also (but related), do the posts should have more than one category? Or one should be the maximum?

**Comment by hermannleboss** [comment]
I think we should use wordpress structure. 

A Post have one or many Category
A Poste have 0 or many Tags 

Category Have 0 or One parent
Category have 0 or many children

**Comment by arnonrdp** [comment]
I think I got a little confused when you said: prompt page and entry page.

Also, you can drag images into here.
