### ISSUE TITLE
[BUG] x 2 while doing user stories. 

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#303]
**Describe the bug**
1) Updating the profile pic, if you chose 'save' and there is an error on the page, it doesn't save but you think it should! The error (in my case choosing my profile name URL) blocks the action. Perhaps on navigating away, or trying to save, there should be some sort of visual cue.

2) When a user is upgraded to a writer -- they are able to change the prompts -- this should be disabled. A 'writer' should only be able to  add / delete / edit their own entries and no one else's. 

**To Reproduce**
1) Create a new user
2) Try to ONLY add their profile and 'saving."

Next,

3) Upgrade the user to "writer" and note what they have control over in the admin panel.

**Smartphone (please complete the following information):**

- Device: Desktop Windows
- Browser Chrome

**Additional context**
Discovered while completing user stories #3 & #4

**Comment by arnonrdp** [comment]
@stravid87, I was not able to reproduce the first error. Could you demonstrate it on video?

The second bug was resolved and is already working in `develop`.
