### ISSUE TITLE
Display unpopulated dates in the Likes chart

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#313]
Currently, the Visitors Graph and Shares Graph displays the data in white, which is nice as it shows the user how long a given article has not had any interaction.

However, this same behaviour is not observed in the Likes/Dislikes graph.

<img width="606" alt="Graphs" src="https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/26576201/41d5ef03-1cb5-427e-b32a-981411f69513">

Note that the bottom graph is correct with the date range empty.

The top graph is incorrect, as it does not display this range.

**Comment by sathudeva7** [comment]
@arnonrdp please review the changes. Thank you!
