### ISSUE TITLE
Integrate SIWE (Sign in with Ethereum) authentication 

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#322]
# SIWE integration
Integrate SIWE (Sign in with Ethereum) authentication into the Celebrity Fanalizer website, allowing users to authenticate with Ethereum credentials, create new accounts, or merge existing accounts.

## Features 

- [ ] Integrate SIWE (Sign in with Ethereum) authentication into Celebrity Fanalizer.
- [ ] Allow new users to create accounts using SIWE credentials.
- [ ] Enable existing users (Firebase Users) to authenticate with SIWE credentials.
- [ ] Implement a process for updating the Celebrity Fanalizer account (Firebase Users)  with SIWE information for existing users.
- [ ] Provide users with the option to merge their SIWE and Celebrity Fanalizer accounts.
- [ ] Offer flexibility for users to sign in with either Firebase or SIWE credentials after merging accounts.

## BDD
**Feature:** SIWE Authentication Integration

**Scenario:** New SIWE User Authentication

**Given** I am a user visiting the Celebrity Fanalizer website
**When** I choose to sign in with SIWE
**And** I provide valid Ethereum credentials
**Then** A request is sent to the SIWE authentication API
**And** If the SIWE user does not exist in Celebrity Fanalizer
**Then** A new user account is created in Celebrity Fanalizer using my SIWE information
**And** I am successfully authenticated on the Celebrity Fanalizer website

**Scenario:** Existing Celebrity Fanalizer User Tries SIWE Authentication

**Given** I am an existing user already authenticated on the Celebrity Fanalizer website
**When** I choose to sign in with SIWE
**And** I provide valid Ethereum credentials
**Then** A request is sent to the SIWE authentication API
**And** If the SIWE user does not exist in Celebrity Fanalizer
**Then** My Celebrity Fanalizer account is updated with my SIWE information
**And** I am successfully authenticated on the Celebrity Fanalizer website

**Scenario:** Existing Celebrity Fanalizer User Tries SIWE Authentication (SIWE User Exists)

**Given** I am an existing user already authenticated on the Celebrity Fanalizer website
**When** I choose to sign in with SIWE
**And** I provide valid Ethereum credentials
**Then** A request is sent to the SIWE authentication API
**And** If the SIWE user already exists on Celebrity Fanalizer
**Then** I am prompted to merge my SIWE account with my Celebrity Fanalizer account
**And** I confirm the merge action
**And** My SIWE account data is merged into my Celebrity Fanalizer account
**And** I am successfully authenticated on the Celebrity Fanalizer website

**Scenario:** Existing Celebrity Fanalizer User Tries SIWE Authentication (SIWE User Exists, No Merge)

**Given** I am an existing user already authenticated on the Celebrity Fanalizer website
**When** I choose to sign in with SIWE
**And** I provide valid Ethereum credentials
**Then** A request is sent to the SIWE authentication API
**And** If the SIWE user already exists on Celebrity Fanalizer
**Then** I am prompted to merge my SIWE account with my Celebrity Fanalizer account
**And** I choose not to merge the accounts
**And** My SIWE account remains separate from my Celebrity Fanalizer account
**And** I am not authenticated on the Celebrity Fanalizer website

**Scenario:** Existing Celebrity Fanalizer User with Merged SIWE Account Can Sign In with Firebase or SIWE

**Given** I am an existing user already authenticated on the Celebrity Fanalizer website
**And** I have previously merged my SIWE account with my Celebrity Fanalizer account
**When** I choose to sign in with Firebase
**Then** I am successfully authenticated with my Firebase credentials
**And** I am granted access to the Celebrity Fanalizer website

**When** I choose to sign in with SIWE
**And** I provide valid Ethereum credentials
**Then** A request is sent to the SIWE authentication API
**And** I am authenticated with my SIWE credentials
**Then** I am successfully authenticated on the Celebrity Fanalizer website
**And** I am granted access to the Celebrity Fanalizer website

**Comment by hermannleboss** [comment]
## Ressources
Chat GPT discussion that can help more. 

https://chat.openai.com/share/247bc8df-5023-49de-b471-73d98f059c16
