### ISSUE TITLE
Logout a user (or real-time update it) when its role is changed;

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#344]
Currently, when a user has their role changed (promoted or demoted), it does not change in real time unless they log out and log in.

We need to solve this by dropping the user or updating their role in real time.

**Comment by sana7044** [comment]
@arnonrdp 
I think we can show a pop-up saying that the roles have been updated, and we need to logout and login again. I believe we need to implement sockets. Any suggestions?

**Comment by arnonrdp** [comment]
I love the idea of a popup.
For realtime updates, we use a function from Firebase called `onSnapshot`.

Take a look at this and take your time: https://firebase.google.com/docs/firestore/query-data/listen
