### ISSUE TITLE
Hide Edit/Delete button if the user doesn't have permission to use it

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#345]
Currently, if you are a writer and access the administrative panel, you see the edit/delete entries disabled buttons.

Instead of being disabled, the ideal is for them to be hidden.

<img width="1680" alt="Captura de Tela 2024-03-17 às 19 00 04" src="https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/26576201/bae7a5da-af1e-4825-82d1-5dd2011886a6">

Important: the buttons should only be hidden if the entry does not belong to the writer.
He should still be able to edit/delete the entries he wrote.

**Comment by sathudeva7** [comment]
@arnonrdp please review the changes. Thanks
