### ISSUE TITLE
Develop increment function for shares

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#39]
When the user taps the share button, we open a small dialog with sharing options on different networks.

The proposal here is to increment the share count whenever one of these buttons is touched.

We just need to decide if the same user will have their shares counted more than once.

Firestore has a specific function for incrementing: https://firebase.google.com/docs/firestore/manage-data/add-data?authuser=0#increment_a_numeric_value

**Comment by stravid87** [comment]
Excellent thought @arnonrdp. 
My immediate choice would be +1 share/platform/user.
So if I share Facebook, that's +1 and if I share WhatsApp that +1 but I cannot share Facebook > 1 time.
The Wordpress Stats engine I'm using is probably a reasonable model to follow. I don't think we need that many platforms represented.

![socialStats](https://user-images.githubusercontent.com/116566901/207628063-980d48cc-4594-40ed-95ac-fb07ec667b2a.png)

**Comment by stravid87** [comment]
@hermannleboss ,  your histogram yesterday came so easy that I have very high expectations now for what the Anthrogram can become haha

`<LikeDislikeBarChart :likes="entry.info.likes.length" :dislikes="entry.info.dislikes.length" class="q-mt-md"/>`

(For the record, making it look easy is a good thing!)

**Comment by arnonrdp** [comment]
> My immediate choice would be +1 share/platform/user.
> So if I share Facebook, that's +1 and if I share WhatsApp that +1 but I cannot share Facebook > 1 time.
> 

Noted! So for the developer who catches this issue:
* it is necessary to store the user's reference in the array of shares;
* But it will also be necessary to store the chosen sharing method.

Check if it's not better a JSON, having as items the ways to share typed as arrays.
In the UI we will display the sum of the lengths of the arrays.

Let's discuss about it if you have doubts.

**Comment by arnonrdp** [comment]
We are not limiting the shares, only the counter of shares for the same social network.

**Comment by hermannleboss** [comment]
OK
