### ISSUE TITLE
[BUG] Month not found error

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#414]
**Describe the bug**
There is an error with the month prompt. Sometimes it doesn't exist, so we must find a way to fix this error.

**Screenshots**
![Captura de Tela 2024-07-05 às 08 37 45](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/26576201/3fca22ba-deaf-4849-a681-c6fb3a5e4fa5)

**Comment by marclupanc** [comment]
I remember fixing this a while ago. Maybe it required some changes. But here is a suggestion fix that is working for me:
In prompts.js for fetchMonthsPrompt()
  
We could first check if we have a prompt for current month:
```
const promptRefCurrent = await getDocs(query(collection(db, 'prompts'), where('id', '==', currentYearMonth())))
const promptSnapshotCurrent = promptRefCurrent.docs.map((doc) => ({ id: doc.id, ...doc.data() }))[0]
```
If we don't have a prompt for current month, we can try searching for a prompt of previous month:

```
if (!promptSnapshotCurrent) {
    const promptRefCurrentPrev = await getDocs(query(collection(db, 'prompts'), where('id', '==', previousYearMonth())))
    const promptSnapshotPrev = promptRefCurrentPrev.docs.map((doc) => ({ id: doc.id, ...doc.data() }))[0]
}

```

Current solution where we try filtering ID so it would be less or equal to current month won't work as the id is a string. Also there is no need to order by date as we anyway search by Id and there can't be two prompts for current month

`
query(collection(db, 'prompts'), orderBy('date', 'desc'), where('id', '<=', currentYearMonth()), limit(1))
`
