### ISSUE TITLE
Create testing 

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/Celebrity-Fanalyzer#42]
We should create tests to avoid changes that break the site if they are not managed.
And we can prevent regressions

**Comment by arnonrdp** [comment]
We will focus on this issue after the release of v1.0.
Tests are good but take a bit of development time.

**Comment by hermannleboss** [comment]
OK

**Comment by stravid87** [comment]
Testing is personally a major weakness of mine.... so I'm gonna give this a go with Vite and Playwrite

**Comment by arnonrdp** [comment]
I am starting working on it based in this: https://testing.quasar.dev/packages/unit-vitest/

**Comment by stravid87** [comment]
God I hate testing... I mean I'm making progress... but God I hate testing.

**Comment by arnonrdp** [comment]
> God I hate testing... I mean I'm making progress... but God I hate testing.

I have to agree, it's pretty boring.
I'm currently trying to connect the staging environment to Firebase.
If our tests don't address Firestore, there's no point in testing anything, so I'm on that quest.

**Comment by arnonrdp** [comment]
@stravid87, are you following my branch?
If so, run `npm run test:unit:ci` to see the tests running. (Of course the main test is failing 🥲)

**Comment by stravid87** [comment]
Nice looks like you've made some excellent headway. I was having trouble where to put all the files (like setup-file.js & install-pinia.ts). 

When I run your branch, I'm getting a strange problem with 'echarts':

```
 FAIL  test/vitest/__tests__/PromptPage.test.ts [ test/vitest/__tests__/PromptPage.test.ts ]
SyntaxError: Unexpected token 'export'
 ❯ Object.compileFunction ../../../node:vm:352:18   
 ❯ Object.<anonymous> node_modules/vue-echarts/dist/index.cjs.min.js:1:97


Module C:/Test_CF_Quasar/Celebrity-Fanalyzer/node_modules/echarts/core.js:20 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "echarts" asking them 
to ship the file in .mjs extension or add "type": "module" in their package.json.

As a temporary workaround you can try to inline the 
package by updating your config:

// vitest.config.js
export default {
  test: {
    deps: {
      inline: [
        "echarts"
      ]
    }
  }
}
```
Are you getting the same?

I spent my day wrapping my head around vueWrapper vs a DOMWrapper -- not the same thing. Just very similar.

**Comment by stravid87** [comment]
Tomorrow's labour: https://test-utils.vuejs.org/guide/essentials/a-crash-course.html

**Comment by arnonrdp** [comment]
Yes, I have the same problem.

I am working on it and looking for a solution.

**Comment by stravid87** [comment]
NOTES ON GETTING YOUR LOCAL EMULATOR RUNNING:
- The JavaSDK is necessary to run Firebase Emulators. Install here: https://www.oracle.com/java/technologies/downloads/#jdk19-windows
- Running just `firebase emulator:start` produced the error: "Error: Cannot start the Authentication Emulator without a project: run 'firebase init' or provide the --project flag". It was necessary to run `firebase emulators:start --project celebrityfanalizer`
- Using the emulator seems to a matter of altering "./src/firebase.js" to import and use the following:
`import { getAuth, connectAuthEmulator } from 'firebase/auth'`
`import { getFirestore, connectFirestoreEmulator } from 'firebase/firestore'`
`import { getStorage, connectStorageEmulator } from 'firebase/storage'` 
- GOTCHA: When you invoke the above functions, your port is NOT the same as the port where you access the UI. For me, this meant accessing the UI @ "http://localhost:4000/auth" but configuring the emulator as follows in 
```
//FILE:  ./src/firebase.js

const localEnv = true
if (localEnv) {
  connectAuthEmulator(auth, 'http://localhost:9099')
  connectFirestoreEmulator(db, 'localhost', 8080)
  connectStorageEmulator(storage, 'localhost', 9199)
}
```
Your specific ports will change and can be found in ".firebase.json"

- Once you're connecting to the emulator appropriately, you'll need to configure the local firestore rules, "./firestrore.rules." I kept it simple and used, 
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}
```
- Don't forget to manually add the <role: 'admin'> to your user in the Firestore user collection.
- And with that.... I CAN ADD PROMPTS AND ENTRIES! 

Phewf....

- To persist data in the emulators & / or export data on shut down: 
`firebase emulators:export <export-directory>`, `firebase emulators:start --export-on-exit`, `firebase emulators:start --import <export-directory>`, `firebase emulators:start --import <export-directory> --export-on-exit`

**Comment by arnonrdp** [comment]
What progress!!!! This is amazing!!

Today I asked @hermannleboss to dip his toes in the `unit-test` branch.

**Comment by stravid87** [comment]
> What progress!!!! This is amazing!!
> 
> Today I asked @hermannleboss to dip his toes in the `unit-test` branch.

Testing (has been) so painful! This should speed his and our entry into it. 

Currently debugging -- I think I'm nearly at a breakthrough. (having trouble mounting <q-editor>)

**Comment by hermannleboss** [comment]
WAO, I miss all this beautiful discussion. 

I think we should work on setup one by one. 

Unit testing
Components testing
Pinia testing
Quasar testing 
And Firebase Testing. 

Some of them have dependencies. 
Ex in our case for Pinia we need Firebase. 

And at the same time we should start documenting our process.

I would like to split this stuff and then understand how it is working.

**Comment by stravid87** [comment]
AAAAAAAAAAAAAAHHHHHHHHHHHHHHHHH:
I'M GOING TO LOSE MY MIND!
if you have this line:  `import { doc, getDoc, runTransaction } from '@firebase/firestore'`
doc(db, 'users', uid) fails (says db is not a firestore?)
the fix is to lose the @ symbol.
if you have this line:  ``import { doc, getDoc, runTransaction } from 'firebase/firestore'``

**Comment by stravid87** [comment]
> 

The division of unit testing; component testing; etc is useful. I'm working on Firebase and next E2E testing. 

Eventually, I think each of us will need to own the full stack of testing for any component we make. That is, if you add functionality, you also add the unit test, component test, pinia test, firebase test and then end-to-end test.

**Comment by arnonrdp** [comment]
Part of me feels guilty for not putting enough hours into this issue.
But the other feels a certain pride to see you dedicating yourself and learning so much from it.

I don't know if you've tried it, but the Quasar Discord server has a specific test channel: https://discord.com/channels/415874313728688138/856517853036675083

**Comment by hermannleboss** [comment]
Nice we will try to get help here

**Comment by stravid87** [comment]
Actually -- Hermann, I think you said to me -- to write good tests means you likely don't need the test. But if you don't / can't write the test, you likely need to test! Suffering through has forced me to learn the app's structure and function. I'm excited to add some tests to the updated dev branch tonight, tomorrow, and Friday. 

I appreciate the support. Still, I'll upload some documentation to make sure you guys don't feel the same pain!

**Comment by stravid87** [comment]
Hard fought:
```
//Firebase
import { auth, db } from '../../firebase'
import { signInWithCredential, GoogleAuthProvider, getAdditionalUserInfo } from 'firebase/auth'

//Testing Frameworks
import { setActivePinia, createPinia } from 'pinia'
import { beforeEach, describe, expect, it } from 'vitest'
import { installQuasar } from '@quasar/quasar-app-extension-testing-unit-vitest'

// Necessary Components
import MainMenu from '../MainMenu.vue'
import { useUserStore } from '../../stores/user'
import { useAuthStore } from '../../stores/auth'
import { mount } from '@vue/test-utils'

installQuasar()

describe('Main Menu Component', () => {
  beforeEach(async () => {
    setActivePinia(createPinia())
    const userStore = useUserStore()
    const userString = '{"sub": "whatSubout?", "email": "algae.peach.153@example.com", "email_verified": true}'
    const credential = GoogleAuthProvider.credential(userString)
    const result = await signInWithCredential(auth, credential)
    const isNewUser = getAdditionalUserInfo(result)?.isNewUser
    const { email, displayName, photoURL, uid } = result.user
    if (isNewUser) {
      await setDoc(doc(db, 'users', uid), { email, displayName, photoURL })
    }
    await userStore.fetchUserProfile(result.user)
  })

  it('should display the admin panel if the user logged has the admin role', async () => {
    const userStore = useUserStore()
    const admin = userStore.isAdmin

    expect(admin).toBe(true)
    let localUserString = localStorage.getItem('user')
    expect(localUserString.indexOf('role')).toBeTruthy()
    const wrapper = mount(MainMenu)
    expect(wrapper.find('[testHandle="adminBtn"]').exists()).toEqual(true)
  })
})
```

**Comment by stravid87** [comment]
### GENERAL INSTRUCTIONS TO ADD TESTING TO A BRANCH / PROJECT
If you build off a branch with testing, some of these instructions may be redundant. 

1. Review & install dependencies in package.json
2. Run `npx quasar ext add @quasar/testing-unit-vitest`
  a. Choose “Extras” only (for now)
  b. Add typescript and other options as desired (Vitest UI)
3. In "./vitest.config.js” change environment to ”jsdom” (instead of "happy-dom")
4. [Optional] delete the folder “test\vitest” or keep it for reference.
5. Modify the firebase.js file ('./src/firebase.js') by adding the following if checks (GOTCHA: check the import statements):
```
const userAnalytics = true
if (userAnalytics) {
  getAnalytics(app)
}

const useEmulators = false
if (useEmulators) {
  connectAuthEmulator(auth, 'http://localhost:9099')
  connectFirestoreEmulator(db, 'localhost', 8000)
  connectStorageEmulator(storage, 'localhost', 9199)
}
```
7. To use Firebase Emulators, you need Java installed. 
8. Modify "./firebase.json" by adding the following object at the top level below "hosting" at the top level of the json object:
```
"emulators": {
    "auth": {
      "port": 9099
    },
    "firestore": {
      "port": 8000
    },
    "hosting": {
      "port": 5000
    },
    "storage": {
      "port": 9199
    },
    "ui": {
      "enabled": true
    }
  },
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "storage": {
    "rules": "storage.rules"
  }
```
8. add the file, "./storage.rules" to the top level domain
```
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth!=null;
    }
  }
}
```
9. Add the file, "./firebase.rules" to the top level domain
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}
```
10. Make sure the cache of your local storage is cleared
11. rename "./.env.development" to just ".env"
12. make sure that the statement: import { doc, getDoc, runTransaction } from '@firebase/firestore' have the '@' symbol removed to read import { doc, getDoc, runTransaction } from 'firebase/firestore'
13. Add the line "src/**/*.spec.js" to vitest.config.js
14. Add the following scripts to package.json
```
"test": "vitest",
"emulators": "firebase emulators:start --project celebrityfanalizer --import emulatorData"
```
15. run `npm run test`

**Comment by arnonrdp** [comment]
It is great!
I notice you added `firebase.json`, `storage.rules` and `firebase.rules` to your branch.

Do you consider it is ready to be reviewed?
Is it updated with the Develop branch?

**Comment by arnonrdp** [comment]
All right, I'll focus on that today.

**Comment by arnonrdp** [comment]
@stravid87, I noticed we have 2 opened PR related to Testing.
Which one is the correct?

And both have conflicts. I need you to solve the conflicts locally first.
If you have any trouble, please let me know.

**Comment by stravid87** [comment]
I closed the merge request with the wrong branch. 
When you mention conflicts, how do you mean?.... oh found it. 
It says just "package.lock.json" is this what you are referring to?

**Comment by arnonrdp** [comment]
Yes, you need to update your branch according to the develop branch:
```sh
# git checkout $your_branch
git merge develop
```

From there the "party" begins. lol
Since the conflict is only in `package-lock.json`, a simple `npm i` can resolve it.
Then you just commit and push.

**Comment by stravid87** [comment]
Got it. Let me try.

**Comment by stravid87** [comment]
K, I think I got it. Learning every day!

**Comment by stravid87** [comment]
The e-charts issue can be handled as follows: 

```
import { defineConfig } from 'vitest/config'
import vue from '@vitejs/plugin-vue'
import { quasar, transformAssetUrls } from '@quasar/vite-plugin'
import jsconfigPaths from 'vite-jsconfig-paths'
import { viteCommonjs } from '@originjs/vite-plugin-commonjs'

// https://vitejs.dev/config/
export default defineConfig({
  test: {
    environment: 'jsdom',
    setupFiles: 'test/vitest/setup-file.js',
    deps: {
      inline: ['vue-echarts', 'echarts']
    },
    include: [
      // Matches vitest tests in any subfolder of 'src' or into 'test/vitest/__tests__'
      // Matches all files with extension 'js', 'jsx', 'ts' and 'tsx'
      'src/**/*.vitest.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}',
      'test/vitest/__tests__/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}',
      'src/**/*.spec.js'
    ]
  },
  plugins: [
    vue({
      template: { transformAssetUrls }
    }),
    quasar({
      sassVariables: 'src/quasar-variables.scss'
    }),
    jsconfigPaths(),
    viteCommonjs(['vue-echarts'])
  ]
})
```

**Comment by stravid87** [comment]
Seeing this merge brings a tear to my eye. 🥲 
Seriously haha. We did it! 1.2!

**Comment by arnonrdp** [comment]
> Seeing this merge brings a tear to my eye. 🥲 Seriously haha. We did it! 1.2!

![image](https://user-images.githubusercontent.com/26576201/222508027-63bacb50-edd7-43f6-8494-f18a9149184a.png)
