### ISSUE TITLE
[BUG] Advertisement card in search page

### ISSUE THREAD

**Issue by marclupanc** [globe-and-citizen/Celebrity-Fanalyzer#423]
When navigating to search page on: 

Mobile device - Google Chrome or Safari
Macbook - Safari

Advertisement card has squared shadow background as displayed in the screenshots below. 
Probably needs some more padding 

![Screenshot 2024-07-10 at 14 53 44](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/43423591/df3265d1-d1f0-4d97-a40b-c73133cfb241)
![IMG_4389](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/43423591/f44aca7e-68b2-4c11-80f0-aec2cf277a4b)

**Comment by arnonrdp** [comment]
Nice catch.
