### ISSUE TITLE
Handle 404 on prompt page

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/Celebrity-Fanalyzer#43]
if we load a prompt page py sending it a wrong id who don't exist in the store and in firestore, we don't have a 404 Error.
Instead of this we have a broken page. 

![image](https://user-images.githubusercontent.com/28951070/206770231-ed80ec4d-6421-4e17-a3af-86a8f86c9070.png)

**Comment by stravid87** [comment]
Okay -- let me take a crack at this.
