### ISSUE TITLE
Package sharePrompt function in a composable, so it should be available every where and we don not have do declare it on every page

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/Celebrity-Fanalyzer#45]
Instead of create shareFunction in every components or page who need the share function we can create it one time by using composable. 

https://vuejs.org/guide/reusability/composables.html

**Comment by arnonrdp** [comment]
@hermannleboss, may I consider this is done?

Your last PR was the composable you planned?

**Comment by arnonrdp** [comment]
@hermannleboss, may I consider this is done?

Your last PR was the composable you planned?

If not, please reopen.

**Comment by hermannleboss** [comment]
> @hermannleboss, may I consider this is done?
> 
> Your last PR was the composable you planned?
> 
> If not, please reopen.

Yes it's completed
