### ISSUE TITLE
Caching Layer for Layer8 AND the PWA in General

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#455]
# Is your feature request related to a problem? Please describe.
Every page reload requires repeat fetched (via the Firebase SDK abstraction layer) to the back. Obviously this hurts performance.

# Describe the solution you'd like
Rock the PWA + indexDB caching functionality (analogous to the layer8-interceptor) to make a local caching layer work#457 

# Notes
This will be completely independent of the Layer8 system.

# Acceptance Criteria
- [ ] Media and content loads once with and expiry of 7(?) days so that a refresh doesn't re-fetch all the data.

**Comment by marclupanc** [comment]
Closing due to duplication. Implementing in #523
