### ISSUE TITLE
Organize Entries by Created

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#470]
Let's do these:
- show the year in the Created column;
- place the most recent at the top;
- make the columns sortable.

![Captura de Tela 2024-08-01 às 10 24 27](https://github.com/user-attachments/assets/63495988-be10-43f1-9688-edacc51cf9cf)

**Comment by pradnyabhukan** [comment]
Hi @arnonrdp,
I was looking into this issue, can you tell me how to login an an admin?
