### ISSUE TITLE
Users should be required to provide an image before submitting

### ISSUE THREAD

**Issue by marclupanc** [globe-and-citizen/Celebrity-Fanalyzer#476]
**Description**
When adding a new entry, users are required to provide an image before submitting. We shold provide a visible indication showing that image is required.

**Current behaviour**
Currently there is no visible indication that image is required when user tries to submit new entry without an image.

**Comment by Arushi-Gupta13** [comment]
Hi, I would like to get this issue assigned. I am a complete beginner looking for issues to resolve. Let me know if I can.
