### ISSUE TITLE
Editing Your Advertisements

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#481]
**Description**
Currently, there is no way to edit an advertisement once deployed. 

An advertiser should be able to:
- Change the advertisement copy (also known as the description / write up)
- Add money to the contract so that the advertisements will still show (after the budge runs out). 

**User Story**
As an advertiser
I want to change the write up that I put on my advertisement or correct and error.
When I navigate to the advertisement page and click the table row that represents my advertisement
I see that I am brought to the familiar editing window. 

**Acceptance Criteria**
An advertiser should be able to do standard CRUD operations on the advertisement.

**Comment by marclupanc** [comment]
Editable ads fixed in #522. Closing this ticket and will reopen a new one for adding budget to contract.
