### ISSUE TITLE
Pinia State Management

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#483]
**Description**
Currently there is room for improvement in the state mgt of the app. I don't yet have details but I know Marc, Javokhir and Daniel have all commented on this. More work will need to be done to turn this issue into real work items.

**Acceptance Criteria**

**Comment by marclupanc** [comment]
Closing due to duplication (partially duplication, it is related to implementing tanstack, that will change the way we approach Pinia)
