### ISSUE TITLE
Organize Columns by Clicking Header

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#485]
**Description**
Especially in the admin panel, there are many tables. These tables can get quite large. Ideally, a user will be able to organize the tables by clicking the top header. of the table to see it get organized alphabetically or numerically highest to low or lowest to high.

![Image](https://github.com/user-attachments/assets/779dd1fe-4453-4c7a-91df-a364be046fe1)

**User Story**

**Acceptance Criteria**

**Comment by marclupanc** [comment]
Fixed in https://github.com/globe-and-citizen/Celebrity-Fanalyzer/pull/473
