### ISSUE TITLE
Add Browser Based Cache

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#504]
**Description**
The goal is to create a PWA caching layer that sits in front of the firebase "getDocs" function.

For Example, in fetchPrompts.js

```

```

**Acceptance Criteria**
- When the user opens the application for the first time, the fetchPrompt and associated functions (fetchPromptById, fetchPromptBySlug, & fetchMonthsPrompt).  A user can then close their browser. 
- The next time the same user opens the application, these functions run but, this time, populate the store using the cache thereby _not,_ invoking the getDocs(...) function.

**Comment by stravid87** [comment]
The getDocs function used by Firebase is not a traditional fetch request. Therefore, the Cache Storage API in the browser will not work. Rather, the IndexDB storage is more appropriate as it can cache general objects. 

Also, note, this task has been split into two: caching of images with the Cache Storage API, Issue # 517

**Comment by marclupanc** [comment]
Closing as this is related to implementing tanstack, ticket #523
