### ISSUE TITLE
Email Sign Up Regex Check

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#508]
**Description**
Currently, ANY string can be submitted as an email ID. This _at least_ should be forced through a regex validation scheme (even if fake)

**Acceptance Criteria**
If the user tries to add a invalid email, they are warned and stopped.

**Comment by arnonrdp** [comment]
@sana7044, you can use Quasar internal validation:
- https://github.com/quasarframework/quasar/blob/dev/ui/src/utils/patterns/patterns.js
- https://quasar.dev/vue-components/input#internal-validation
