### ISSUE TITLE
Uploading Images of Various Sizes

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#56]
Doing testing today for stravid87/why, Issue #50, I came across the challenge of uploading only square images. 

I think in time we'll need to update this to allow for a variety of sizes -- or at least in-moment cropping. Even for me, it's substantial work to resize an image.  

To solve this issue, a solution will be necessary to allow for the upload of images of any shape. Size (in terms of KB) should be enforced but the dimension should be flexible.

**Comment by arnonrdp** [comment]
This makes sense.

The best option would be to have a built-in cropping tool. But that would take a little time.

So I will accept images of any dimensions and only limit the size to 5MB.

**Comment by stravid87** [comment]
In the first version(s), we will have near full control over all content published. That is to say, authors and artists will submit to us and then we'll post. So it does not need to be a priority now.

**Comment by arnonrdp** [comment]
Fixed this one.

We will probably back to this one in the future with a crop method.

**Comment by stravid87** [comment]
Awesome. The good news is that errors, bugs, and inconveniences are all tolerable in our early stages as only us, the team, will be using the Content Management Side of the app.
