### ISSUE TITLE
[FEAT] Replace Matic To Polygon Network

### ISSUE THREAD

**Issue by marclupanc** [globe-and-citizen/Celebrity-Fanalyzer#594]
**Description**
We need to change Matic Network to Polygon

**Comment by achillegley** [comment]
we don't really have big changes to make. we just need to change the strings "MATIC" in our code bae to "POL". that's all

**Comment by marclupanc** [comment]
I guess it is already done in #484

**Comment by marclupanc** [comment]
> we don't really have big changes to make. we just need to change the strings "MATIC" in our code bae to "POL". that's all

Can you take care of it? 🤔
