### ISSUE TITLE
Create a Public Discussion Board on Discord

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#6]
GOAL: We need a public discussion board on discord where people / participants on the site can start to comment / participate in choosing next months question / topic of discussion. 

REQUIREMENTS: Whoever does this needs to learn how to set appropriate permissions so that our team discussion is not compromised. Whoever picks up this project, please teach me how to add a link to the Celebrity Fanalyzer home page. 

TIMELINE: Flexible. 

DELIVERABLE: An overview of how the channel is set up and working.

**Comment by arnonrdp** [comment]
Team channels are already private.
In fact, the **general** and **others** categories are private to **administrators**. So any channels created within those categories will also be private.

You can right click on the channel or category and go to **permissions**.

There you can view all roles/members that can access that particular channel/category.

I've made channels in the celebrity analyzer category public.
Let me know if you need any more modifications. If not, I believe you can close this issue.

**Comment by stravid87** [comment]
Hi @arnonrdp 
You are correct. After taking a peek and doing my own research, this is pretty simple to close / complete. 
It's on my list of things to do to modify the home page on the Wordpress site to point to the discord channel and slowly start soliciting suggestions from the writers / readers.

**Comment by arnonrdp** [comment]
Excellent idea!
