### ISSUE TITLE
Can't Load the current month prompt. 

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/Celebrity-Fanalyzer#64]
## We can't load the current mont prompt. 

When i try to debug to find why i find.
- We are using prompt.id in this format **2023-01**  and we check it using this format  **2023-1**
- And the second error is we stor the month from **1-12** and we check it using **0-11**

**Comment by arnonrdp** [comment]
I couldn't reproduce it. Here this is loading fine.
Could you share a vid, gif or image?

**Comment by arnonrdp** [comment]
Guys, made some changes to avoid errors when loading month prompt.
@globe-and-citizen/team-1-test Please clean your local storages in browser console > aplicattion.
