### ISSUE TITLE
Delete likes/dislikes/shares collection when deleting Prompt/Entry

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/Celebrity-Fanalyzer#65]
When deleting Prompt or Entries the associated likes/dislikes are not being deleted
---

Because likes/dislikes are a dedicate document in prompt or entries they are not deleted when we delete prompts or entries. 
So we have orphan document in Firestore.

![image](https://user-images.githubusercontent.com/28951070/211168646-ccd4e751-2a79-4161-af57-695ccf661047.png)

**Comment by arnonrdp** [comment]
We need to wait your branch to be merged before diving into this issue.

**Comment by arnonrdp** [comment]
We will have the following orphaned collections when a prompt or entry is deleted:
- likes;
- dislikes;
- shares;
- comments

Therefore, in the next few days I will make some commits related to this, so that whenever a Prompt or Entry is deleted, all these subcollections are also deleted.

**Comment by arnonrdp** [comment]
@NJavokhir, please check the functions I created for likes and shares that delete the entire collection and, if you can, adopt a similar approach to comments.
If in doubt, let me know.
