### ISSUE TITLE
Improve file size after build

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#7]
File sizes need to be improved after build.

In addition to resolving the build warning, it will make the application lighter in the production environment.

![Captura de Tela 2022-11-14 às 17 55 35](https://user-images.githubusercontent.com/26576201/201763714-fd7986c7-5b0f-42ca-8733-20b7018bb195.png)

**Comment by stravid87** [comment]
Working on this now. I have got the components lazy loading. For example, in AdminPage.vue:

`const PromptCard = defineAsyncComponent(() => import('src/components/PromptCard.vue'))`
`const EntryCard = defineAsyncComponent(() => import('src/components/EntryCard.vue'))`

However, it didn't make much of any dent in the main problem: "assets/index.e38d0e0d.js │ 592.58 KB │ 159.48 KB"

Looking into it now how to fix this.

**Comment by arnonrdp** [comment]
This one is not easy.

**Comment by arnonrdp** [comment]
Solved by adding this to the build:
```js
extendViteConf(viteConf) {
  viteConf.build.rollupOptions = {
    output: {
      manualChunks(id) {
        const chunks = ['@quasar/extras', 'firebase', 'pinia', 'quasar', 'vue', 'vue-router']
        if (id.includes('/node_modules/')) {
          for (const chunkName of chunks) {
            if (id.includes(chunkName)) {
              return chunkName
            }
          }
        }
      }
    }
  }
}
```

**Comment by arnonrdp** [comment]
> I'm gonna take partial credit for finding "extendViteConf(viteConf)" haha well done.

You deserve. 💪
