### ISSUE TITLE
Building Out the Anthrogram

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#8]
![Image](https://user-images.githubusercontent.com/116566901/201960692-b70e5d13-625e-4b88-bc12-3372d8c14bfd.jpg)

The statistics page (that is available for all entries/posts) is what I call an "Anthrogram." This issue is about getting this functionality built.

BACKGROUND: When the app first goes live, users will not need to log in. From them we can only get their general location(? @arnonrdp ) and their reaction to the content to show as statistics. To begin with, we can just focus on likes / dislikes and not worry about geography or anything else.

GOAL: Build a very simple statistics page & discussion page that shows on swipe left / right.

PROPOSED ROLES: 
-- @stravid87 build a wireframe and Figma design file.
-- @hermannleboss  turn the Figma design file into a feature branch that @arnonrdp can merge into the main app

OTHER INFO:
"Anthrogram" is a word that I made up. "Anthro" means "person", "gram" means "display/view/representation". So _Anthro-gram_ means _person-representation_.

**Comment by stravid87** [comment]
https://www.figma.com/proto/QhLrjceQDns5TDt7JzUpUE/Anthrogram-Wireframe?node-id=1330%3A6260&scaling=scale-down&page-id=1330%3A5888&starting-point-node-id=1330%3A6260&show-proto-sidebar=1

**Comment by arnonrdp** [comment]
I believe we can integrate Google Analytics to Anthrogram considering we are using Sign in with Google.

For those user who decide to login we will have exact location, gender, age, etc…

I will check what data we have for non-logged users.

**Comment by stravid87** [comment]
Awesome. @hermannleboss how do you feel about starting with simple time series data for likes / dislikes and them upgrading to presenting the non-sensitive details we can get from Google analytics perhaps?

**Comment by hermannleboss** [comment]
Yes it"s a good idea

**Comment by arnonrdp** [comment]
I would say we have the foundation.

Now, @hermannleboss and I are talking about how the data should be stored in the DB considering that for each reaction click we need to store date/time, user (or IP), prompt (or entry) and like (or dislike). Did I miss something?

**Comment by hermannleboss** [comment]
No that's right.

**Comment by arnonrdp** [comment]
The first "step" of this issue is completed. It's about having the basic information of a prompt/entry displayed in the graph.

The next step will be a new issue with more details of the next charts. We'll take care of that in the next release.
