### ISSUE TITLE
Make the stats page more UI friendly

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#84]
In the mobile version of the statistics page the title of the content (prompt/entry) is bigger than the title of the toolbar.

The user's name (when large) is below the photo and ideally I was side by side with it.

![Captura de Tela 2023-02-02 às 15 47 13](https://user-images.githubusercontent.com/26576201/216421024-1eef16b7-d9eb-4f33-9bc7-3f509a077234.png)

**Comment by hermannleboss** [comment]
OK got it.
