### ISSUE TITLE
User Updates Do Not Persist Unless User Logs Out / Logs back In

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#88]
Occurs for picture, bio, & data

How to recreate: 
1. Open a new account / log in.
2. Add a bio. 
3. Navigate to another page. 
4. Navigate back to the user page. 
5. Bio will be gone. Firestore DB will be correct. 
6. Log out / log in and it appears.

**Comment by arnonrdp** [comment]
Directly committed to the `develop` branch due to simplicity.
