### ISSUE TITLE
No Universal Back Button + Reusable Toolbar

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#91]
No universal back button is enabled and for users of mobile devices, this will cause frustration.

**Comment by arnonrdp** [comment]
I need to understand this better.

`vue-router` has a [history mode](https://router.vuejs.org/guide/essentials/history-mode.html) and should work well for mobile back and forward buttons.

What kind of problem did you have with that?

**Comment by stravid87** [comment]
When loading as a PWA (or in different browser contexts), there is no guarantee where the back button will be. 
My thought, taken from if I remember correctly the Pintrest app, is the use of an in app universal back button at the top left corner. This keeps the interface always 100% consistent across all contexts, sizes, devices, etc. It's just a standard "back" button -- except we do it in App and not rely on the external button.

**Comment by stravid87** [comment]
Before I start in on the coding, I'll do up some mocks and solicit your feedback.

**Comment by arnonrdp** [comment]
Sound great to me.

**Comment by stravid87** [comment]
I have sketches in Fort McMurray so I'll be making progress on this next week.

**Comment by stravid87** [comment]
So looking at the sketches, appears that Reddit, Medium, & Pintrest all have the universal back button. It's nothing special. Just a back button always found in the topmost left hand side.

**Comment by stravid87** [comment]
Looking at our application, the Home page, Search Page and profile page all have a floating top Header. Where the logo is on the home page I think could be ideal. Replace the logo with the stylized back button and then simply put it on all the pages? I would maintain symmetry and give users the constant ability to navigate backwards which I think does lots for usability.

**Comment by arnonrdp** [comment]
I got your point. A back button can be useful. I think it will be fine!
Do you want to take care of it or do you want me to?

**Comment by stravid87** [comment]
I know it will take me a morning to learn and execute properly. For you it's probably very easy. 
I'm again banging my head against testing. Better use of our time you doing it I think (if you have time).
Thanks!

**Comment by arnonrdp** [comment]
Yes, of course.
I will do it.

**Comment by arnonrdp** [comment]
I will try to create a reusable toolbar for all pages and put the back button inside it.

**Comment by stravid87** [comment]
As expected haha. Very nice. I notice it's missing from the prompt? Was this intentional?
 
I notice on smaller phones it's getting crowded -- I can only assume this is why there was no menu before. I posted a video in discord. Of all the apps, Medium deals with this the best. If you see the video, on scroll down the menus disappear. On scroll up, they re-appear. With Quasar, how hard to achieve this effect?

**Comment by stravid87** [comment]
Also, regarding Medium, they did something very clever. When you open the developer console, there is a console log that says, "We're hiring!" with a link to their hiring page. I loved this because only those who know about the developer console will see it. In time we need to have one too. One that says, "Don't hack us. Join us!" with our link.

**Comment by arnonrdp** [comment]
> As expected haha. Very nice. I notice it's missing from the prompt? Was this intentional?

Long back I didn't added the toolbar to PromptPage because it was not included in the mock.

---
 
> I notice on smaller phones it's getting crowded -- I can only assume this is why there was no menu before. I posted a video in discord. Of all the apps, Medium deals with this the best. If you see the video, on scroll down the menus disappear. On scroll up, they re-appear. With Quasar, how hard to achieve this effect?

I can apply this effect.

---

> Also, regarding Medium, they did something very clever. When you open the developer console, there is a console log that says, "We're hiring!" with a link to their hiring page. I loved this because only those who know about the developer console will see it. In time we need to have one too. One that says, "Don't hack us. Join us!" with our link?

I loved that idea! Haha
