### ISSUE TITLE
Error Loading My Entries

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#92]
Entries show in the app. Entries show in Firebase but the entries don't show but for 2? 
Author is correct in Firebase.

![Screenshot_of_failed entry load](https://user-images.githubusercontent.com/116566901/216496424-565f7ebc-8cdd-4c04-9bb4-7c05caadb938.jpg)

**Comment by arnonrdp** [comment]
I fixed that bug, please let me know if you are able to load all entries this time.

**Comment by stravid87** [comment]
Yup. Works!
