### ISSUE TITLE
Share Prompt/Entry directly in the App

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#93]
I notice that there is no way to "share" on Discord when the social share button is clicked.

---

> @arnonrdp:
> It is possible to open a mobile app just using JavaScript.
> 
> So I think it would be a good idea to open the app he chose when he tapped share.
> 
> Assuming that the user is accessing our application through a mobile browser, this is the step-by-step:
> - The user opens a prompt (or entry);
> - The user presses the share button and watches a mini-window go up;
> - User taps social media icon to share that link, then:
>    - **How is it today:**
>      - A new browser tab opens with the chosen link;
>      - The user sees a text and the share link;
>    - **How ​​should be:**
>      - The application chosen by the user is opened;
>      - The user sees a text and the share link;
> 
> 
> Some conditions will be required to check if the user is using web or mobile device. If you are on a web device, nothing will change, everything will continue to work the way it is. Only if it's on a mobile device will the magic happen.

**Comment by tarunsamanta2k20** [comment]
Please assign this issue to me.

**Comment by arnonrdp** [comment]
Welcome @tarunsamanta2k20. Now it's "yours".
Feel free to collaborate with us and improve our documents if you feel the need.

**Comment by tarunsamanta2k20** [comment]
@arnonrdp i am adding discord share option

**Comment by NJavokhir** [comment]
I have a lot of researched and I couldn't find individual url scheme for sharing on discord. What is your thoughts @arnonrdp @stravid87 @hermannleboss

**Comment by stravid87** [comment]
> 

I think you simply share the a link to a channel no? So a Discord  "Share button" is really just the link. If you wanted to "share" it, you would post the link to standard other social media no? I created a link to the general channel. You can use this one: `https://discord.gg/z4P3UrhhSH`

**Comment by arnonrdp** [comment]
We already have a button to join our Discord channel.

In this case here we want to share a prompt/entry in a Discord channel. In fact, I don't know if it's possible to do that.

When the user is on the cell phone, the ideal would be in some way that we can open his application. But if that's not possible, it might be better to close this issue.

**Comment by stravid87** [comment]
I'm studying discord right now. 

Looking at the channel.... there might be a way to integrate it with Webhooks.... (kind of like the way Github Pushes ring the Discord). I don't know this needs to be priority though.  @NJavokhir thoughts on closing this issue?

**Comment by NJavokhir** [comment]
Now, I added discord share button when social share button is clicked. If user click discord button, his discord app will be opened on phone or web browser.

**Comment by stravid87** [comment]
> Now, I added discord share button when social share button is clicked. If user click discord button, his discord app will be opened on phone or web browser.

Traveling at the moment. I'll look forward to seeing that. 

If it works with no errors, then I'm supportive.

**Comment by arnonrdp** [comment]
Folks, I'm pushing this issue to the 1.2 release.

The reason is that it is still not working as it should. The link simply opens Discord, but does not and does not offer any way on how to share the prompt/entry.

Through mobile devices I saw that it is possible to open an application. I tested it and it really works.

<img width="550" alt="222241537-8a44af8e-aaef-4bef-aa4f-4e74366e9503 (1)" src="https://user-images.githubusercontent.com/26576201/222242386-15e5b68b-87af-42e9-9c05-6d905636a314.png">

So I'm going to evolve this issue with some ideas I had and update it.

**Comment by stravid87** [comment]
> Folks, I'm pushing this issue to the 1.2 release.
> 
> The reason is that it is still not working as it should. The link simply opens Discord, but does not and does not offer any way on how to share the prompt/entry.
> 
> Through mobile devices I saw that it is possible to open an application. I tested it and it really works.
> 
> <img alt="222241537-8a44af8e-aaef-4bef-aa4f-4e74366e9503 (1)" width="550" src="https://user-images.githubusercontent.com/26576201/222242386-15e5b68b-87af-42e9-9c05-6d905636a314.png">
> 
> So I'm going to evolve this issue with some ideas I had and update it.

Is that..... ChatGPT?! Wow, the future is now....
(As I envision it, we are going to have very low organic traffic for now. We're not close to any critical mass of users and we don't necessarily want to be at this time. 1.2 is just fine with me).

**Comment by NJavokhir** [comment]
I am so excited about ChatGPT. I could not find solution for this problem. That is really amazing future. I will try to do on 1.2 release.

**Comment by arnonrdp** [comment]
Yes, this is ChatGPT, sometimes I ask some stuff to ~him~ it.
@NJavokhir do you want to be developer of it?

**Comment by NJavokhir** [comment]
Yes, I want

**Comment by stravid87** [comment]
@arnonrdp & @NJavokhir. Let's close this issue? I'm thinking to focus more on making the user interface robust for the writing team before we focus on sharing widely. I don't like when checklists get too long: bothers my OCD. So thinking we should just close for now?

**Comment by arnonrdp** [comment]
Yes, I think we can postpone this one.
